# Set all versions
ZEN_BUILD_TYPE ?= UNOFFICIAL
ZEN_DATE_YEAR := $(shell date -u +%Y)
ZEN_DATE_MONTH := $(shell date -u +%m)
ZEN_DATE_DAY := $(shell date -u +%d)
ZEN_DATE_HOUR := $(shell date -u +%H)
ZEN_DATE_MINUTE := $(shell date -u +%M)
ZEN_BUILD_DATE_UTC := $(shell date -d '$(ZEN_DATE_YEAR)-$(ZEN_DATE_MONTH)-$(ZEN_DATE_DAY) $(ZEN_DATE_HOUR):$(ZEN_DATE_MINUTE) UTC' +%s)
ZEN_BUILD_DATE := $(ZEN_DATE_YEAR)$(ZEN_DATE_MONTH)$(ZEN_DATE_DAY)-$(ZEN_DATE_HOUR)$(ZEN_DATE_MINUTE)
ZEN_PLATFORM_VERSION := 9.0
ZenOS_VERSION := BETA

TARGET_PRODUCT_SHORT := $(subst zen_,,$(ZEN_BUILD))

ifeq ($(IS_GO_VERSION), true)
ZEN_VERSION := ZenOS_go_$(ZEN_BUILD)-$(ZEN_PLATFORM_VERSION)-$(ZEN_BUILD_DATE)-$(ZEN_BUILD_TYPE)
ZEN_FINGERPRINT := ZenOS_go/$(ZEN_PLATFORM_VERSION)/$(ZEN_PRODUCT_SHORT)/$(ZEN_BUILD_DATE)
else
ZEN_VERSION := ZenOS_$(ZEN_BUILD)-$(ZEN_VERSION)-$(ZEN_BUILD_DATE)-$(ZEN_BUILD_TYPE)
ROM_FINGERPRINT := ZenOS/$(ZEN_PLATFORM_VERSION)/$(ZEN_PRODUCT_SHORT)/$(ZEN_BUILD_DATE)
endif

ZEN_PROPERTIES := \
    org.zen.version=$(ZenOS_VERSION) \
    org.zen.build_date=$(ZEN_BUILD_DATE) \
    org.zen.build_date_utc=$(ZEN_BUILD_DATE_UTC) \
    org.zen.build_type=$(ZEN_BUILD_TYPE) \
    org.zen.fingerprint=$(ZEN_FINGERPRINT)
